# roles/mailserver/handlers/main.yml
---

- name: restart_postfix
  systemd:
    name: "{{ mailserver_postfix_service }}"
    state: restarted

- name: restart_dovecot
  systemd:
    name: "{{ mailserver_dovecot_service }}"
    state: restarted